version: '3'

services:
  nuxt:
    # Dockerfileの場所
    build: .
    # コンテナ起動時のコマンド
    command: npm run dev
    # ローカルとコンテナ内とでソースコードを共有
    volumes:
      - .:/jamstack-cms
    # ポートを指定
    ports:
      - "8080:3000"
    # 環境変数を設定（ホストからコンテナ内にアクセスできるように）
    environment:
      HOST: "0.0.0.0"